### PR TITLE
Invalid schema

### PR DESCRIPTION
**Pull request by bcouston**
Replacement of conditional statement to see if a regular expression was
created with a RegexpError rescue to catch when creation failed and act
accordingly.

### CODE REVIEW

**Comment by bcouston** [comment]
DO NOT MERGE. Tests pass, but app gets stuck in an endless loop if you try to validate a schema with an invalid regular expression pattern. Need some help from @Floppy  or @pezholio to pin this down.

**Comment by pezholio** [comment]
Hey @bcouston - try running `bundle exec rake jobs:work` as well as the app server. Validations are carried out as background jobs to prevent requests timing out on the frontend

**Comment by bcouston** [comment]
@pezholio I'm still getting a hang up, it keeps making the same request, any ideas?
screen shot 2015-07-14 at 09 53 57

**Comment by pezholio** [comment]
Yeah, it should keep polling that request until the validation is created. What does the console output of `rake jobs:work` say?

**Comment by bcouston** [comment]
[Worker(host:Bens-MacBook-Air.local pid:45708)] Job Package#create_package (id=55a4cdb442656eb33c000003) FAILED (4 prior attempts) with RegexpError: premature end of char-class: /[/

So the RegexpError is causing it to hang, can I get the app to execute the code in the rescue block and carry on with normal operation? @pezholio

**Comment by pezholio** [comment]
Ah, looks like the Regexp error is happening in the app, rather than here. I think catching that with a begin ... rescue block should be fine

**Comment by bcouston** [comment]
[link text](https://github.com/theodi/csvlint.rb/blob/e8606d52455cbdd19add11311eefb637d5b8ccd8/lib/csvlint/field.rb#L45-L54) @pezholio I've already implemented one, is there anywhere I've made a mistake?

**Comment by pezholio** [comment]
Ah, no, the code here is fine. It seems that there's an error happening in the CSVlint app. I'll have a dig.

**Comment by bcouston** [comment]
I just had change the link for the csvlint gem in the Gemfile in csvlint to refer the branch I was working on (invalid-schema)

**Comment by pezholio** [comment]
Cool cool, is this good to go then?

**Comment by bcouston** [comment]
@pezholio at the moment, it raises an invalid regular expression error for every record in the csv that doesn't match the invalid regex (so every one). It would be a a lot cleaner if it was raised once and other errors/warnings concerning regex were not displayed, as an invalid regex form in the schema probably takes priority. Thoughts?

**Comment by pezholio** [comment]
Yeah, I think it's only sufficient to show the error once

**Comment by bcouston** [comment]
@pezhelio on it

**Comment by bcouston** [comment]
DO NOT MERGE until reviewed further.

**Comment by pezholio** [comment]
Cool, this looks good now. We'll need to add support for this in the Csvlint app too, so I won't merge just yet, especially as we have a few more PRs open

**Pull request merged**
