### PR TITLE
Streaming validation

### PR DESCRIPTION
**Pull request by pezholio**
Opening a PR for @quadrophobiac's work

### CODE REVIEW

**Comment by quadrophobiac** [comment]
The streaming validator is typified by the specs added in ```context "with a single row"```and context ```context "validation with multiple lines: "```  
Both of these spec contexts test various ways that the Validator_Stream object can be initialised and then it's various methods can be used to validate a CSV  
the `def validate` method has been preserved in the interest of creating a validator that would be backwards compatible with the old code base, see line 43  
Alternatively as the specs demonstrate each of the `validate_metadata` `report_line_breaks` and `parse_contents` methods can be invoked independently to generate errors and warnings  
Both `parse_contents` and `validate_metadata` can be invoked with enumerable behaviour which was the aim with a method that could take a CSV line by line and report errors  
see `streaming_validator_spec.rb:130` and `streaming_validator_spec.rb:157`

**Comment by kwent** [comment]
Pretty awesome ! It this included this feature ? https://github.com/theodi/csvlint.rb/issues/143

**Comment by pezholio** [comment]
Yup, that's the plan!

**Comment by kwent** [comment]
@pezholio Awesome ! Do we have an ETA of when this will be merged in master and the gem version updated ?

**Comment by pezholio** [comment]
I'm working on it as we speak. Hoping to get it done for the end of the week :+1:

**Comment by kwent** [comment]
@pezholio Awesome ! Can't wait.

**Comment by quadrophobiac** [comment]
These tests are now failing on a single feature `features/validation_errors.feature:126` - error of `:stray_quote` returned instead of `:line_breaks`
This hinges on logic 
```ruby
      if !@csv_options[:row_sep].kind_of?(Symbol) && type == :unclosed_quote && !@input.match(@csv_options[:row_sep])
        build_linebreak_error
``` 
within validate.rb https://github.com/theodi/csvlint.rb/blob/19dc4244dabd90aa4789f08be42d3edd59546668/lib/csvlint/validate.rb#L290

In the case of the feature this fails because `type` is reported as unclosed_quote

changes to this logic (to recognise `:stray_quote`) will adversely affect https://github.com/theodi/csvlint.rb/blob/19dc4244dabd90aa4789f08be42d3edd59546668/spec/validator_spec.rb#L248

The string which the exception builder receives is `"\"Foo\",\"Bar\",\"Baz\"\r\"Biff\",\"Baff\",\"Boff\"\r\"Qux\",\"Teaspoon\",\"Doge\""` - no obviously unclosed quote

**Comment by kwent** [comment]
\o/ :+1: +:100:

**Pull request merged**
