### PR TITLE
Fixes line content incorrectly being put into the row column field when there is an encoding error.

### PR DESCRIPTION
**Pull request by glacier**

### CODE REVIEW

**Comment by glacier** [comment]
Can someone review this? I'm hoping to ship this gem in my codebase and I'd really need to get this bug fixed. Thanks!

**Comment by pezholio** [comment]
Done. Thanks for the PR! :smile:

**Comment by pezholio** [comment]
I'll give you a shout when I've bumped the release in Rubygems

**Comment by pezholio** [comment]
This is now live in Rubygems https://rubygems.org/gems/csvlint/versions/0.1.1

**Comment by glacier** [comment]
@pezholio thank you for merging! Thank you! Does this mean that if I get the updated gem now, it'll have the fix?

**Comment by pezholio** [comment]
Yup :smile:

**Pull request merged**
